use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// A subagent written once in Markdown with YAML front matter.
#[derive(Debug, Clone, PartialEq)]
pub struct AgentDef {
    pub source: PathBuf,
    pub name: String,
    pub description: String,
    pub body: String,
}

impl AgentDef {
    pub fn stem(&self) -> String {
        self.source
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| self.name.clone())
    }

    pub fn file_name(&self) -> String {
        self.source
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| format!("{}.md", self.name))
    }
}

pub fn parse_agent(source: &Path, text: &str) -> AgentDef {
    let stem = source
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_default();
    let (front, body) = split_front_matter(text);
    let fields = parse_fields(front.unwrap_or(""));
    AgentDef {
        source: source.to_path_buf(),
        name: fields.get("name").cloned().unwrap_or(stem),
        description: fields.get("description").cloned().unwrap_or_default(),
        body: body.to_string(),
    }
}

/// Codex subagents are TOML with the prompt in `developer_instructions`.
pub fn render_codex_toml(agent: &AgentDef) -> String {
    let mut out = format!(
        "# Generated by agents-sync from {}. Edit the source, not this file.\n",
        agent.source.display()
    );
    out.push_str(&format!("name = {}\n", toml_string(&agent.name)));
    out.push_str(&format!(
        "description = {}\n",
        toml_string(&agent.description)
    ));
    if agent.body.contains("'''") {
        out.push_str(&format!(
            "developer_instructions = {}\n",
            toml_string(&agent.body)
        ));
    } else {
        out.push_str(&format!(
            "developer_instructions = '''\n{}'''\n",
            agent.body
        ));
    }
    out
}

fn toml_string(value: &str) -> String {
    toml::Value::String(value.to_string()).to_string()
}

fn split_front_matter(text: &str) -> (Option<&str>, &str) {
    let Some(rest) = text
        .strip_prefix("---\n")
        .or_else(|| text.strip_prefix("---\r\n"))
    else {
        return (None, text);
    };
    let mut offset = 0;
    for line in rest.split_inclusive('\n') {
        if line.trim_end_matches(['\r', '\n']) == "---" {
            let body = &rest[offset + line.len()..];
            return (Some(&rest[..offset]), body.trim_start_matches(['\r', '\n']));
        }
        offset += line.len();
    }
    (None, text)
}

/// The small YAML subset agent files use: `key: value`, quoted values, and
/// folded (`>`) or literal (`|`) blocks.
fn parse_fields(front: &str) -> BTreeMap<String, String> {
    let lines: Vec<&str> = front.lines().collect();
    let indented = |line: &str| line.starts_with([' ', '\t']) || line.trim().is_empty();
    let mut fields = BTreeMap::new();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        i += 1;
        if indented(line) {
            continue;
        }
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let value = value.trim();
        let parsed = if matches!(value, ">" | ">-" | "|" | "|-") {
            let mut parts = Vec::new();
            while i < lines.len() && indented(lines[i]) {
                if !lines[i].trim().is_empty() {
                    parts.push(lines[i].trim());
                }
                i += 1;
            }
            parts.join(if value.starts_with('>') { " " } else { "\n" })
        } else {
            unquote(value)
        };
        fields.insert(key.trim().to_string(), parsed);
    }
    fields
}

fn unquote(value: &str) -> String {
    let quoted = value.len() >= 2
        && ((value.starts_with('"') && value.ends_with('"'))
            || (value.starts_with('\'') && value.ends_with('\'')));
    if quoted {
        value[1..value.len() - 1].to_string()
    } else {
        value.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn folded_descriptions_are_joined_on_one_line() {
        let agent = parse_agent(
            Path::new("/a/x.md"),
            "---\nname: x\ndescription: >-\n  first\n  second\n---\nbody\n",
        );
        assert_eq!(agent.description, "first second");
        assert_eq!(agent.body, "body\n");
    }

    #[test]
    fn a_body_with_triple_quotes_falls_back_to_an_escaped_string() {
        let agent = AgentDef {
            source: "/a/x.md".into(),
            name: "x".into(),
            description: "d".into(),
            body: "say '''hi'''\n".into(),
        };
        let parsed: toml::Value = toml::from_str(&render_codex_toml(&agent)).unwrap();
        assert_eq!(
            parsed["developer_instructions"].as_str(),
            Some("say '''hi'''\n")
        );
    }
}
